language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - conda activate test-environment
  - conda install --file requirements.txt
  - conda install pytest-cov
  - python setup.py install

script:
  - pytest -v --cov=pyosp --cov-report=term-missing
   