language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - conda activate test-environment
  - conda install -c conda-forge --file requirements.txt
  - conda install -c conda-forge pytest-cov coveralls
  - python setup.py install

script:
  - pytest -v --cov=pyosp --cov-report=term-missing

after_script:
  - python setup.py clean

after_success:
  - coveralls || echo "!! intermittent coveralls failure"

notifications:
  email: false
   