package:
  name: pyosp
  version: "0.1.0"

source:
  path: ..

requirements:
  build:
    - python >=3.5,{{PY_VER}}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - numpy >=1.19*
    - matplotlib >=3.3*
    - gdal >=2.3*
    - shapely >=1.6*
    - pytest

about:
  home: https://github.com/PyOSP-devs/PyOSP.git
  license: apache 2.0
  license_file: LICENSE